export const ACCOUNT = '/account'
export const COMPONENTS = '/components'
export const DASHBOARD = '/dashboard'
export const LANDING = '/'
export const PASSWORD_FORGET = '/pw-forget'
export const TODOS = '/todos'
