export const LANDING = '/'
// export const REGISTER = '/signup'
// export const LOGIN = '/login'
export const PASSWORD_FORGET = '/pw-forget'
export const COURSES = '/courses'
export const DASHBOARD = '/dashboard'
export const ACCOUNT = '/account'
export const NEWDOC = '/new'
